services:
  - type: web
    name: my-flask-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn run:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: "sqlite:///instance/app.db"
