"""empty message

Revision ID: 853af1467730
Revises: 51ace24762f8
Create Date: 2024-07-11 16:56:36.386608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853af1467730'
down_revision = '51ace24762f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticket_price', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('tickets_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('ticket_price', sa.FLOAT(), nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('event_date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('tickets_remaining', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('events')
    # ### end Alembic commands ###
