"""users migration

<<<<<<<< HEAD:migrations/versions/9289b104ebd6_users_migration.py
Revision ID: 9289b104ebd6
Revises: 
Create Date: 2024-07-09 10:04:05.099925
========
Revision ID: c4fcd20ebf3b
Revises: 
Create Date: 2024-07-07 19:40:10.860862
>>>>>>>> 3e608c08d31840a0dc354bd4886d6ce1c1f82804:migrations/versions/c4fcd20ebf3b_initial_migration.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/9289b104ebd6_users_migration.py
revision = '9289b104ebd6'
========
revision = 'c4fcd20ebf3b'
>>>>>>>> 3e608c08d31840a0dc354bd4886d6ce1c1f82804:migrations/versions/c4fcd20ebf3b_initial_migration.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
