"""initial commit

Revision ID: c83c1218fd92
Revises: b16aafb9c378
Create Date: 2024-07-17 16:12:45.501252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c1218fd92'
down_revision = 'b16aafb9c378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the column with a default value
        batch_op.add_column(sa.Column('jwt_key', sa.String(length=255), nullable=False, server_default='default_jwt_key'))

    # Remove the default value after adding the column
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('jwt_key', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('jwt_key')
    # ### end Alembic commands ###
